### 1 导入numpy库并简写为 np 

In [313]:
import numpy as np

In [314]:
### 2 打印numpy的版本和配置说明

In [315]:
print(np.__version__)

1.16.4


### 3 创建一个长度为10的空向量 

In [316]:
a = np.empty(10)

In [317]:
a

array([0.85926316, 0.82961271, 0.55998465, 0.56655716, 0.67561299,
       0.58560711, 0.30816121, 0.11856985, 0.9563196 , 0.04124945])

### 4 如何找到任何一个数组的内存大小？

In [318]:
print(a.size)

10


In [319]:
print(a.itemsize)

8


In [320]:
print(a.size * a.itemsize)

80


### 5 如何从命令行得到numpy中add函数的说明文档? 

In [321]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### 6 创建一个长度为10并且除了第五个值为1的空向量 

In [322]:
a = np.empty(10)
a[4] = 1
print(a)

[0.85926316 0.82961271 0.55998465 0.56655716 1.         0.58560711
 0.30816121 0.11856985 0.9563196  0.04124945]


### 7 值域范围 10 ～ 49 的向量

In [323]:
a =np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8 反转一个向量

In [324]:
a = np.arange(50)

In [325]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [326]:
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 9 创建一个 3x3 并且值从0到8的矩阵

In [327]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [328]:
a.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [329]:
index = np.nonzero([1,2,0,0,4,0])
print(index)

(array([0, 1, 4]),)


### 11 创建一个 3x3 的单位矩阵

In [330]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12 创建一个 3x3x3的随机数组

In [331]:
a = np.random.random((3, 3, 3))
a

array([[[0.36680522, 0.71986934, 0.48094224],
        [0.94311723, 0.56680547, 0.64848842],
        [0.66043788, 0.74477493, 0.92196676]],

       [[0.36321125, 0.92851358, 0.35334841],
        [0.69290374, 0.07123589, 0.81268741],
        [0.27700238, 0.63736328, 0.42907022]],

       [[0.53519338, 0.29900987, 0.84775109],
        [0.31462097, 0.97713812, 0.4126722 ],
        [0.38160755, 0.599807  , 0.67666053]]])

### 13 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [332]:
a = np.random.random((10, 10))
print(a.min(), a.max())

0.0018965210423048662 0.9827726346060751


### 14 创建一个长度为30的随机向量并找到它的平均值

In [333]:
a = np.random.random(30)
print(a.mean())

0.5555734177082187


### 15 创建一个二维数组，其中边界值为1，其余值为0 

In [334]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 16 对于一个存在在数组，如何添加一个用0填充的边界?

In [335]:
a = np.ones((5, 5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [336]:
a = np.ones((5, 5))
a = np.pad(a, pad_width=2, mode='constant', constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 17 以下表达式运行的结果分别是什么?

In [337]:
'''
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
'''

'\n0 * np.nan\nnp.nan == np.nan\nnp.inf > np.nan\nnp.nan - np.nan\n0.3 == 3 * 0.1\n'

In [338]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 18 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [339]:
a = np.diag(1 + np.arange(4))
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [340]:
a = np.diag(1 + np.arange(4), k =-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [341]:
a = np.diag(1 + np.arange(4), k =-2)
a

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0]])

In [342]:
a = np.diag(1 + np.arange(4), k =1)
a

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [343]:
a = np.diag(1 + np.arange(4), k =0)
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 19 创建一个8x8 的矩阵，并且设置成棋盘样式

In [344]:
a = np.zeros((8, 8), dtype = int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [345]:
# Python sequence slice addresses can be written as a[start:end:step] and any of start, stop or end can be dropped.

In [346]:
a = np.zeros((8, 8), dtype = int)
a[1::2, ::2] = 1
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 20 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [347]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


### 21 用tile函数去创建一个 8x8的棋盘样式矩阵

In [348]:
np.info(np.tile)

 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an array.
br

In [349]:
a = np.array([[1, 0], [0, 1]])
a

array([[1, 0],
       [0, 1]])

In [350]:
z = np.tile(a, (4, 4))
z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 22 对一个5x5的随机矩阵做归一化

In [351]:
a = np.random.random((5, 5))
a

array([[0.65718262, 0.4239219 , 0.79758647, 0.6719646 , 0.01522302],
       [0.84447964, 0.39081409, 0.38048061, 0.9846249 , 0.77438002],
       [0.45483344, 0.31132975, 0.19528248, 0.35409979, 0.54551426],
       [0.67985574, 0.5201813 , 0.83481451, 0.6728439 , 0.98089775],
       [0.15986088, 0.75593824, 0.73026062, 0.63622942, 0.53353249]])

In [352]:
amax, amin = a.max(), a.min()

In [353]:
a = (a - amin) / (amax - amin)
a

array([[0.66222235, 0.42159901, 0.8070579 , 0.67747091, 0.        ],
       [0.8554312 , 0.38744619, 0.37678655, 1.        , 0.78311897],
       [0.45348624, 0.30545302, 0.18574284, 0.34957305, 0.5470293 ],
       [0.68561112, 0.52089674, 0.84546101, 0.67837797, 0.9961552 ],
       [0.14920319, 0.76409509, 0.73760698, 0.64060779, 0.53466934]])

### 23 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [354]:
color = np.dtype(
                    [
                        ('r', np.ubyte, 1),
                        ('g', np.ubyte, 1),
                        ('b', np.ubyte, 1),
                        ('a', np.ubyte, 1)
                    ]
                )

In [355]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### 24 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [356]:
a = np.ones((5, 3))
b = np.ones((3, 2))
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [357]:
z = np.dot(a, b)
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 25 给定一个一维数组，对其在3到8之间的所有元素取反(符号取反)

In [358]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [359]:
a > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [360]:
a <= 8

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False])

In [361]:
(a > 3) & (a <= 8)

array([False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [362]:
1 & 0 # 位运算

0

In [363]:
a[(a > 3) & (a <= 8)]

array([4, 5, 6, 7, 8])

In [364]:
a[(a > 3) & (a <= 8)] * -1

array([-4, -5, -6, -7, -8])

### 26 下面脚本运行后的结果是什么? 

In [365]:
'''
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
'''

'\nprint(sum(range(5),-1))\nfrom numpy import *\nprint(sum(range(5),-1))\n'

In [366]:
sum(range(5))

10

In [367]:
print(sum(range(5), -1))

10


In [368]:
from numpy import sum

In [369]:
print(sum(range(5), -1))

10


### 27 考虑一个整数向量Z,下列表达合法的是哪个?

In [370]:
a = np.array([1, 2])

In [371]:
a ** a

array([1, 4])

In [372]:
2 << a

array([4, 8])

In [373]:
a >> 2

array([0, 0])

In [374]:
a < -a

array([False, False])

In [375]:
1j + a

array([1.+1.j, 2.+1.j])

In [376]:
a / 1 / 1

array([1., 2.])

In [377]:
a < a

array([False, False])

In [378]:
a > a

array([False, False])

In [379]:
a < a > a

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [380]:
b = np.array([3, 2])
b ** b

array([27,  4])

In [381]:
b >> 1

array([1, 1])

### 28 下列表达式的结果分别是什么?

In [382]:
np.array(0) / np.array(0)

nan

In [383]:
np.array(0) // np.array(0)

0

In [384]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [385]:
np.array([np.nan])

array([nan])

In [386]:
np.array([np.nan]).astype(int)

array([-9223372036854775808])

### 29 如何从零位对浮点数组做舍入 ?

In [387]:
a = np.random.uniform(-10, +10, 10)
a

array([-4.74801147, -5.08132577, -1.25059226, -4.0496392 ,  8.80266866,
        3.15603714, -7.65141438,  4.81344374,  3.62300762,  9.47682965])

In [388]:
print(np.copysign(np.ceil(np.abs(a)), a))

[-5. -6. -2. -5.  9.  4. -8.  5.  4. 10.]


### 30 如何找到两个数组中的共同元素?

In [389]:
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 10, 10)
print(a)
print(b)

[2 7 3 7 8 0 9 2 6 7]
[2 3 0 2 5 3 6 8 3 7]


In [390]:
np.intersect1d(a, b)

array([0, 2, 3, 6, 7, 8])

### 31 如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [391]:
defaults = np.seterr(all='ignore')
a = np.ones(1) / 0

In [392]:
_ = np.seterr(**defaults)

In [393]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

### 32 下面的表达式是正确的吗?

In [394]:
np.sqrt(-1)

nan

In [395]:
np.emath.sqrt(-1)

1j

In [396]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

### 33 如何得到昨天，今天，明天的日期?

In [397]:
today = np.datetime64('today', 'D')
today

numpy.datetime64('2019-08-07')

In [398]:
np.timedelta64(1, 'D')

numpy.timedelta64(1,'D')

In [399]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
yesterday

numpy.datetime64('2019-08-06')

In [400]:
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
tomorrow

numpy.datetime64('2019-08-08')

### 34 如何得到所有与2016年7月对应的日期？

In [401]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

### 35 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? 

In [402]:
a = np.ones(3) *1
a

array([1., 1., 1.])

In [403]:
b = np.ones(3) * 2
b

array([2., 2., 2.])

In [404]:
c = np.ones(3) * 3
c

array([3., 3., 3.])

In [405]:
np.add(a, b, out=b)

array([3., 3., 3.])

In [406]:
b

array([3., 3., 3.])

In [407]:
np.negative(a,out=a)

array([-1., -1., -1.])

In [408]:
a

array([-1., -1., -1.])

In [409]:
np.multiply(a,b,out=a)

array([-3., -3., -3.])

In [410]:
a

array([-3., -3., -3.])

In [411]:
b

array([3., 3., 3.])

### 36 用五种不同的方法去提取一个随机数组的整数部分

In [412]:
a = np.random.uniform(0, 10, 10)
a

array([9.11778931, 9.3442316 , 1.40486267, 8.07110965, 9.27737429,
       0.9275303 , 9.19807906, 6.61135723, 0.61592895, 0.24238122])

In [413]:
print(a - a % 1)

[9. 9. 1. 8. 9. 0. 9. 6. 0. 0.]


In [414]:
a % 1

array([0.11778931, 0.3442316 , 0.40486267, 0.07110965, 0.27737429,
       0.9275303 , 0.19807906, 0.61135723, 0.61592895, 0.24238122])

In [415]:
print(np.floor(a))

[9. 9. 1. 8. 9. 0. 9. 6. 0. 0.]


In [416]:
print(np.ceil(a) - 1)

[9. 9. 1. 8. 9. 0. 9. 6. 0. 0.]


In [417]:
np.ceil(a)

array([10., 10.,  2.,  9., 10.,  1., 10.,  7.,  1.,  1.])

In [418]:
print(a.astype(int))

[9 9 1 8 9 0 9 6 0 0]


In [419]:
print(np.trunc(a))

[9. 9. 1. 8. 9. 0. 9. 6. 0. 0.]


### 37 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [420]:
a = np.zeros((5, 5))

In [421]:
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 38 通过考虑一个可生成10个整数的函数，来构建一个数组

In [422]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [423]:
a = np.linspace(0, 1, 11, endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### 40 创建一个长度为10的随机向量，并将其排序

In [424]:
a = np.random.random(10)
a.sort()
a

array([0.03073942, 0.11441731, 0.16823468, 0.17314575, 0.20444083,
       0.54376549, 0.59915819, 0.82512729, 0.85290906, 0.8562773 ])

### 41 对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [425]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [426]:
np.add.reduce(a)

45

### 42 对于两个随机数组A和B，检查它们是否相等

In [427]:
a = np.random.randint(0, 2, 5)
a

array([0, 0, 0, 1, 1])

In [428]:
b = np.random.randint(0, 2, 5)
b

array([1, 0, 1, 1, 1])

In [429]:
equal = np.allclose(a, b)

In [430]:
equal

False

In [431]:
equal = np.array_equal(a, b)

In [432]:
equal

False

### 43 创建一个只读数组(read-only)

In [433]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

### 44 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [434]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.91973254 0.41510545 0.86419235 1.21466017 0.94450821 0.43528339
 0.84032242 0.15218321 0.73345498 1.10247779]
[0.6868586  0.7956506  0.22415354 0.85305819 1.17062526 0.00410707
 1.34236352 0.0909057  0.91588876 0.90790578]


### 45 创建一个长度为10的向量，并将向量中最大值替换为1

In [435]:
a = np.random.random(10)
a

array([0.69740116, 0.08146068, 0.46184548, 0.20264874, 0.10305255,
       0.63921566, 0.59500983, 0.67084341, 0.87744042, 0.04950335])

In [436]:
a.argmax()

8

In [437]:
a[a.argmax()] = 1

### 46 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [438]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [439]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


### 48 打印每个numpy标量类型的最小值和最大值？

In [440]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49 如何打印一个数组中的所有数值? 

In [441]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

### 50 给定标量时，如何找到数组中最接近标量的值？

In [442]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

49
